---
- name: "update apt"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade apt packages"
  become: true
  apt:
    upgrade: "yes"

- name: "Remove packages that are no longer used"
  become: true
  apt:
    autoremove: yes

- name: "install dependencies."
  become: true
  apt:
    name: ["tar", "unzip", "curl", "git"]
    state: latest
    update_cache: yes

- name: "install dependencies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present 
