---
- name: install tar
  become: yes
  apt:
    name: tar
    state: latest
    update_cache: yes


- name: "Add nodejs 13.x"
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash 
    sudo apt-get install -y nodejs
    
- name: Install nodejs
  become: yes
  apt:
   update_cache: yes
   name: nodejs
   state: present

- name: install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes
    
- name: prapare backend
  shell: |
    cd /home/ubuntu/
    mkdir backend
   

- name: copy built backend files
  become: yes
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend

- name: Extract backend
  shell: |
    cd /home/ubuntu/backend
    tar -xzvf artifact.tar.gz
- name: Start pm2
  shell: |    
    npm i
    pm2 stop default
    pm2 start npm -- start
