---
- name: install tar
  become: yes
  apt:
    name: tar
    state: latest
    update_cache: yes

- name: copy built backend files
  become: yes
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: Extract backend
  shell: |
    cd /home/ubuntu/
    tar xvzf artifact.tar.gz -C .
    
    
- name: Start pm2
  shell: |    
    cd /home/ubuntu/
    npm i
    pm2 stop default
    pm2 start npm -- start
